import Head from "next/head";
import { Inter } from "next/font/google";
import { Center, Box } from '@mantine/core';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <Center maw={400} h={100} bg="var(--mantine-color-gray-light)">
          <Box bg="var(--mantine-color-blue-light)">All elements inside Center are centered</Box>
        </Center>
      </main>
    </>
  );
}
